import type { Activity } from './domain';

const sourceDocument = '2024 Adult Compendium of Physical Activities';
const sourceVersion = '2024 Adult Compendium（成人版）';
const sourceUrl = 'https://pacompendium.com/wp-content/uploads/2025/02/1_2024-adult-compendium_1_2024.pdf';
const evidenceRelation = 'この引用はMETs値と活動内容の根拠です。';

// Demo subset. The production import keeps every master row and must preserve sourceCode.
export const activities: Activity[] = [
  { id: 'walk-normal', name: '歩行（やや速め）', description: '駅や待ち合わせへ、少し急いで向かうような歩き方です（アプリ内の目安）。', sourceQuote: 'Walking, 2.8 to 3.4 mph, level, moderate pace, firm surface', sourceTranslation: '平らで硬い路面を、中程度のペースで歩く（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '歩く', mets: 3.8, sourceCode: '17190', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['散歩', 'ウォーキング', 'やや速めに歩く'], ease: 1 },
  { id: 'dog-walk', name: '犬の散歩', description: '犬と一緒に歩く活動です。', sourceQuote: 'Walking the dog', sourceTranslation: '犬の散歩（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '歩く', mets: 3.0, sourceCode: '17165', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['散歩', 'ペット'], ease: 1.5 },
  { id: 'walk-goal', name: '歩行（目標に入る目安）', description: 'のんびり散歩ではなく、平らな道を止まらず一定のペースで歩くイメージです（アプリ内の目安）。', sourceQuote: 'Walking, 2.5 mph, firm, level surface', sourceTranslation: '平らで硬い路面を、一定のペースで歩く（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '歩く', mets: 3.0, sourceCode: '17170', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['散歩', 'ウォーキング', '目標に入る歩行'], ease: 2 },
  { id: 'nature-walk', name: '野原・丘の散策', description: '大きな荷物を持たず、野原や緩やかな丘をゆっくり散策する活動です。山登りほどではない散策のイメージです。', sourceQuote: 'Hiking slowly or ambling through fields and hillsides, no load', sourceTranslation: '荷物を持たず、野原や丘陵をゆっくりハイキングまたは散策する（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '散策', mets: 3.8, sourceCode: '17081', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['散策', 'ハイキング', '野山', '丘', 'トレイル'], ease: 2.3 },
  { id: 'housework', name: '床・カーペットを掃く', description: '床やカーペットを掃く活動です。', sourceQuote: 'Cleaning, sweeping carpet or floors, general', sourceTranslation: '掃除：カーペットまたは床を掃く、一般（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '家事', mets: 3.3, sourceCode: '05010', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['掃除', '床掃除'], ease: 2.5 },
  { id: 'vacuuming-general', name: '掃除機をかける', description: '掃除機を使って床などを掃除する活動です。', sourceQuote: 'Vacuuming, general, moderate effort', sourceTranslation: '掃除機をかける、一般、中程度の負荷（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '家事', mets: 3.0, sourceCode: '05043', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['掃除機', '掃除'], ease: 2.6 },
  { id: 'stretch', name: 'ストレッチ', description: '体をゆっくり伸ばす活動です。', sourceQuote: 'Stretching, mild', sourceTranslation: '軽いストレッチ（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '運動', mets: 2.3, sourceCode: '02101', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['柔軟', '体操'], ease: 2.8 },
  { id: 'weeding', name: '草むしり', description: '庭などで適度な力で草を抜く活動です。', sourceQuote: 'Weeding, cultivating garden, moderate effort (Taylor Code 580)', sourceTranslation: '草むしり、庭の手入れ、中程度の負荷（Taylorコード580）（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '庭仕事', mets: 4.5, sourceCode: '08240', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['庭仕事'], ease: 3 },
  { id: 'crunch', name: '腹筋（クランチ）', description: '腹筋運動の一例としてクランチを行います。まずは10回が開始目安です（回数はアプリ内目安）。', sourceQuote: 'Body weight resistance exercises (e.g., squat, lunge, push-up, crunch), general', sourceTranslation: '自重を使うレジスタンス運動（例：スクワット、ランジ、腕立て伏せ、クランチ）、一般（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '運動', mets: 3.0, sourceCode: '02056', sourceDocument, sourceVersion, verificationStatus: '照合済み', repetitionGuide: '開始目安：まず10回（回数はアプリ内目安）', aliases: ['腹筋', 'クランチ', '筋トレ'], ease: 4 },
  { id: 'squat', name: 'スクワット', description: '自重のスクワットを行います。まずは10回が開始目安です（回数はアプリ内目安）。', sourceQuote: 'Body weight resistance exercises (e.g., squat, lunge, push-up, crunch), general', sourceTranslation: '自重を使うレジスタンス運動（例：スクワット、ランジ、腕立て伏せ、クランチ）、一般（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '運動', mets: 3.0, sourceCode: '02056', sourceDocument, sourceVersion, verificationStatus: '照合済み', repetitionGuide: '開始目安：まず10回（回数はアプリ内目安）', aliases: ['筋トレ', '下半身'], ease: 4.1 },
  { id: 'lunge', name: 'ランジ', description: '自重のランジを行います。左右5回ずつが開始目安です（回数はアプリ内目安）。', sourceQuote: 'Body weight resistance exercises (e.g., squat, lunge, push-up, crunch), general', sourceTranslation: '自重を使うレジスタンス運動（例：スクワット、ランジ、腕立て伏せ、クランチ）、一般（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '運動', mets: 3.0, sourceCode: '02056', sourceDocument, sourceVersion, verificationStatus: '照合済み', repetitionGuide: '開始目安：左右5回ずつ（回数はアプリ内目安）', aliases: ['筋トレ', '片足スクワット'], ease: 4.2 },
  { id: 'push-up', name: '腕立て伏せ', description: '自重の腕立て伏せを行います。まずは5回が開始目安です（回数はアプリ内目安）。', sourceQuote: 'Body weight resistance exercises (e.g., squat, lunge, push-up, crunch), general', sourceTranslation: '自重を使うレジスタンス運動（例：スクワット、ランジ、腕立て伏せ、クランチ）、一般（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '運動', mets: 3.0, sourceCode: '02056', sourceDocument, sourceVersion, verificationStatus: '照合済み', repetitionGuide: '開始目安：まず5回（回数はアプリ内目安）', aliases: ['腕立て', '筋トレ'], ease: 4.3 },
  { id: 'walk-fast', name: '速歩', description: '腕を振って意識的にテンポよく歩きます。人によっては走り出す手前に感じる速さです（アプリ内の目安）。', sourceQuote: 'Walking, 3.5 to 3.9 mph, level, brisk, firm surface, walking for exercise', sourceTranslation: '平らで硬い路面を、運動として速いペースで歩く（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '歩く', mets: 4.8, sourceCode: '17200', sourceDocument, sourceVersion, verificationStatus: '照合済み', aliases: ['速歩', 'ウォーキング', '速く歩く'], ease: 5 },
  { id: 'side-step', name: 'サイドステップ（低衝撃エアロビクス）', description: '左右へのサイドステップを、低衝撃の室内運動として行います。左右10往復が開始目安です（回数はアプリ内目安）。', sourceQuote: 'Aerobic dance, low impact, moderate effort', sourceTranslation: 'エアロビックダンス、低衝撃、中程度の負荷（参考訳・アプリ）。', sourceUrl, evidenceRelation: 'サイドステップ自体は引用行に直接記載されておらず、低衝撃エアロビクスを具体化したアプリ内メニューです。引用はMETs値と活動分類の根拠です。', category: '運動', mets: 4.8, sourceCode: '02005', sourceDocument, sourceVersion, verificationStatus: '照合済み', repetitionGuide: '開始目安：左右10往復（回数はアプリ内目安）', aliases: ['サイドステップ', '横ステップ', '室内運動'], ease: 3.5 },
  { id: 'jumping-jack', name: 'ジャンピングジャック（その場運動）', description: 'その場でジャンピングジャックを行う高強度の運動です。まずは10回が開始目安です（回数はアプリ内目安）。', sourceQuote: 'Calisthenics (e.g., pushups, sit ups, pull-ups, jumping jacks, burpees, battling ropes), vigorous effort', sourceTranslation: '自重運動（例：腕立て伏せ、腹筋、懸垂、ジャンピングジャック、バーピー、バトルロープ）、高強度（参考訳・アプリ）。', sourceUrl, evidenceRelation, category: '運動', mets: 7.5, sourceCode: '02020', sourceDocument, sourceVersion, verificationStatus: '照合済み', repetitionGuide: '開始目安：まず10回（回数はアプリ内目安）', aliases: ['ジャンピングジャック', 'その場ジャンプ', '室内運動'], ease: 6 },
];
